### ISSUE TITLE
이미지 등이 있는 문단 복사시 NullPointerException 가 발생합니다.

### ISSUE THREAD

**Issue by hama0511** [neolord0/hwplib#100]
좋은 오픈소스 정말 감사드립니다.

[1.hwp.zip](https://github.com/neolord0/hwplib/files/5529209/1.hwp.zip)
[2.hwp.zip](https://github.com/neolord0/hwplib/files/5529217/2.hwp.zip)

2파일은 서식만 있는 빈문서 파일입니다.
이미지나 셀이 없는 경우는 카피가 잘 됩니다
```
        HWPFile sourceHWPFile = HWPReader.fromFile("1.hwp");
        HWPFile targetHWPFile = HWPReader.fromFile("2.hwp");

        if (sourceHWPFile != null && targetHWPFile != null) {

            ParagraphListInterface targetFirstSection = targetHWPFile.getBodyText().getSectionList().get(0);
            {
                ArrayList<Section> sectionList = sourceHWPFile.getBodyText().getSectionList();

                ParagraphAdder paraAdder = new ParagraphAdder(targetHWPFile, targetFirstSection);
                for (Section section : sectionList) {
                    for (int i = 0; i < section.getParagraphCount(); i++) {
                        Paragraph sourceParagraph = section.getParagraph(i);

                        paraAdder.add(sourceHWPFile, sourceParagraph);
                    }
                }
            }

            HWPWriter.toFile(targetHWPFile, "merge.hwp");
        }
```

```
java.lang.NullPointerException
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.shadowEffect(GsoCopier.java:217)
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.pictureEffect(GsoCopier.java:210)
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.picture(GsoCopier.java:195)
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.copy(GsoCopier.java:46)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copyControlList(ParagraphCopier.java:95)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copy(ParagraphCopier.java:47)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphAdder.add(ParagraphAdder.java:45)
	at Main.main(Main.java:30)
java.lang.NullPointerException
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.StyleAdder.equal(StyleAdder.java:39)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.StyleAdder.findFromTarget(StyleAdder.java:30)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.StyleAdder.processById(StyleAdder.java:19)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParaHeaderCopier.copy(ParaHeaderCopier.java:17)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copyHeader(ParagraphCopier.java:53)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copy(ParagraphCopier.java:42)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphAdder.add(ParagraphAdder.java:45)
	at Main.main(Main.java:30)
java.lang.NullPointerException
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.StyleAdder.equal(StyleAdder.java:39)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.StyleAdder.findFromTarget(StyleAdder.java:30)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.StyleAdder.processById(StyleAdder.java:19)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParaHeaderCopier.copy(ParaHeaderCopier.java:17)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copyHeader(ParagraphCopier.java:53)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copy(ParagraphCopier.java:42)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphAdder.add(ParagraphAdder.java:45)
	at Main.main(Main.java:30)
java.lang.NullPointerException
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.StyleAdder.equal(StyleAdder.java:39)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.StyleAdder.findFromTarget(StyleAdder.java:30)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.StyleAdder.processById(StyleAdder.java:19)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParaHeaderCopier.copy(ParaHeaderCopier.java:17)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copyHeader(ParagraphCopier.java:53)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copy(ParagraphCopier.java:42)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphAdder.add(ParagraphAdder.java:45)
	at Main.main(Main.java:30)
java.lang.NullPointerException
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.StyleAdder.equal(StyleAdder.java:39)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.StyleAdder.findFromTarget(StyleAdder.java:30)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.StyleAdder.processById(StyleAdder.java:19)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParaHeaderCopier.copy(ParaHeaderCopier.java:17)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copyHeader(ParagraphCopier.java:53)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copy(ParagraphCopier.java:42)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphAdder.add(ParagraphAdder.java:45)
	at Main.main(Main.java:30)
java.lang.NullPointerException
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.shadowEffect(GsoCopier.java:217)
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.pictureEffect(GsoCopier.java:210)
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.picture(GsoCopier.java:195)
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.copy(GsoCopier.java:46)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copyControlList(ParagraphCopier.java:95)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copy(ParagraphCopier.java:47)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphAdder.add(ParagraphAdder.java:45)
	at Main.main(Main.java:30)
java.lang.NullPointerException
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.shadowEffect(GsoCopier.java:217)
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.pictureEffect(GsoCopier.java:210)
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.picture(GsoCopier.java:195)
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.copy(GsoCopier.java:46)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copyControlList(ParagraphCopier.java:95)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copy(ParagraphCopier.java:47)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphAdder.add(ParagraphAdder.java:45)
	at Main.main(Main.java:30)
java.lang.IndexOutOfBoundsException: Index 6 out of bounds for length 6
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:373)
	at java.base/java.util.ArrayList.get(ArrayList.java:426)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.BinDataAdder.processById(BinDataAdder.java:32)
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCommonPartCopier.pictureInfo(GsoCommonPartCopier.java:195)
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.picture(GsoCopier.java:192)
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.copy(GsoCopier.java:46)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copyControlList(ParagraphCopier.java:95)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copy(ParagraphCopier.java:47)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphAdder.add(ParagraphAdder.java:45)
	at Main.main(Main.java:30)
Exception in thread "main" java.lang.NullPointerException
	at kr.dogfoot.hwplib.writer.HWPWriter.isCompressBinData(HWPWriter.java:215)
	at kr.dogfoot.hwplib.writer.HWPWriter.embeddedBinaryData(HWPWriter.java:202)
	at kr.dogfoot.hwplib.writer.HWPWriter.binData(HWPWriter.java:180)
	at kr.dogfoot.hwplib.writer.HWPWriter.toFile(HWPWriter.java:43)
	at Main.main(Main.java:40)

```

**Comment by neolord0** [comment]
이 부분은 기능을 추가하다가 테스트를 하지 못 했는데.  오류가 나네요..
오류 수정 했습니다. 다시 받아서 테스트 해보세요.

**Comment by hama0511** [comment]
아 정말 완벽합니다. 감사합니다.
