### ISSUE TITLE
컨트롤찾기 이미지가 있을시 NullPointerException

### ISSUE THREAD

**Issue by urlence** [neolord0/hwplib#109]
문서에 테이블 컨트롤과 이미지 컨트롤이 있고, 
Finding_Control.java를 이용해 테이블 컨트롤을 찾고자 할 경우,
NullPointer 에러가 납니다.

```
Exception in thread "main" java.lang.NullPointerException
	at kr.dogfoot.hwplib.tool.objectfinder.ControlFinder.forRectangle(ControlFinder.java:262)
	at kr.dogfoot.hwplib.tool.objectfinder.ControlFinder.forGso(ControlFinder.java:229)
	at kr.dogfoot.hwplib.tool.objectfinder.ControlFinder.forParagraphInControl(ControlFinder.java:115)
	at kr.dogfoot.hwplib.tool.objectfinder.ControlFinder.forParagraph(ControlFinder.java:100)
	at kr.dogfoot.hwplib.tool.objectfinder.ControlFinder.forParagraphList(ControlFinder.java:83)
	at kr.dogfoot.hwplib.tool.objectfinder.ControlFinder.go(ControlFinder.java:69)
	at kr.dogfoot.hwplib.tool.objectfinder.ControlFinder.find(ControlFinder.java:53)
	at com.wert.report.util.hwp.sample.Finding_Control.main(Finding_Control.java:36)
```
제가 작업중인 프로젝트에 이미지를 삽입한뒤 테이블 컨트롤 찾기를 하면 NullPointer 에러가 발생해
오늘 올려주신 예제 Inserting_Table_WithImageBack.java 에서 테스트 해봤으나 같은 에러가 납니다.
올려주신 예제로 파일을 만든 뒤, Finding_Control.java를 이용해 테이블 컨트롤을 찾을려고 시도했습니다.

**Comment by neolord0** [comment]
제가 테스트 해 보기로는 문제가 없는데..
테스트하신 코드랑 hwp 파일을 올려주세요..

**Comment by urlence** [comment]
코드와 파일 첨부해서 메일로 보냈습니다.

**Comment by neolord0** [comment]
제가 textbox객체가 Null일 때 처리를 하지 않은 거 같군요.
수정하여 올렸습니다

**Comment by urlence** [comment]
감사합니다!
