### ISSUE TITLE
문단 복사 시 getBaseFontName()을 가져올 수 없습니다.

### ISSUE THREAD

**Issue by seopchan** [neolord0/hwplib#123]
[layout.hwp.zip](https://github.com/neolord0/hwplib/files/5923295/layout.hwp.zip)
[srcHWP.zip](https://github.com/neolord0/hwplib/files/5923309/srcHWP.zip)

layout파일에 src파일들을 각각 복사하려고 합니다.

srcHWP파일들을 각각 테스트 하면 모두 아래와 같은 에러가 발생합니다.
>Exception in thread "main" java.lang.NullPointerException
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.FaceNameAdder.equal(FaceNameAdder.java:51)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.FaceNameAdder.equalByHangulId(FaceNameAdder.java:137)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.CharShapeAdder.equalFaceNameIds(CharShapeAdder.java:56)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.CharShapeAdder.equal(CharShapeAdder.java:39)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.CharShapeAdder.findFromTarget(CharShapeAdder.java:31)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.CharShapeAdder.processById(CharShapeAdder.java:20)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParaCharShapeCopier.copy(ParaCharShapeCopier.java:15)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copyCharShape(ParagraphCopier.java:67)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copy(ParagraphCopier.java:44)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphAdder.add(ParagraphAdder.java:45)
	at kr.dogfoot.hwplib.src.MergeTest.main(MergeTest.java:38)

[1.zip](https://github.com/neolord0/hwplib/files/5923382/1.zip)
위 1번 파일의 경우 정상적으로 getBaseFontName을 할 때 나눔고딕을 얻을 수 있지만
srcHWP의 파일들의 경우 getBaseFontName이 null로 나옵니다....

테스트에 사용한 코드입니다.
```
if (sourceHWPFile != null && targetHWPFile != null) {
            ArrayList<Section> sectionList = targetHWPFile.getBodyText().getSectionList();

            ParagraphListInterface targetFirstSection = sectionList.get(0);
            Section targetSection = sourceHWPFile.getBodyText().getSectionList().get(0);
            for (int i = 0; i < targetSection.getParagraphCount(); i++) {
                Paragraph sourceParagraph = targetSection.getParagraph(i);
                ParagraphAdder paraAdder = new ParagraphAdder(targetHWPFile, targetFirstSection);

                if (i == 0) {
                    String firstLine = sourceParagraph.getNormalString();
                    sourceParagraph.deleteText();
                    sourceParagraph.createText();
                    String newFirstLine = "1. " + firstLine;
                    sourceParagraph.getText().addString(newFirstLine);

                    Paragraph targetLastParagraph = targetFirstSection.getParagraph(targetFirstSection.getParagraphCount() - 1);
                    paraAdder.merge(targetLastParagraph, sourceHWPFile, sourceParagraph);
                } else {
                    paraAdder.add(sourceHWPFile, sourceParagraph);
                }
            }
            HWPWriter.toFile(targetHWPFile, "new" + sourceFileName);
        }
```

**Comment by neolord0** [comment]
Null 체크를 안 한 거 같습니다.. 수정하였습니다.

**Comment by seopchan** [comment]
테스트 해보았고 잘 작동합니다.
감사합니다!!
