### ISSUE TITLE
문단 복사 시 Bullet을 가져올 수 없습니다.

### ISSUE THREAD

**Issue by seopchan** [neolord0/hwplib#124]
[layout.hwp.zip](https://github.com/neolord0/hwplib/files/5923337/layout.hwp.zip)
[srcHWP.zip](https://github.com/neolord0/hwplib/files/5923340/srcHWP.zip)

layout파일에 src파일들을 각각 복사하려고 합니다.

srcHWP파일들을 각각 테스트 하면 모두 아래와 같은 에러가 발생합니다. 
>Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.BulletAdder.processById(BulletAdder.java:19)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.ParaShapeAdder.setParaHead(ParaShapeAdder.java:104)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.ParaShapeAdder.addAndCopy(ParaShapeAdder.java:81)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.ParaShapeAdder.processById(ParaShapeAdder.java:21)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParaHeaderCopier.copy(ParaHeaderCopier.java:16)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copyHeader(ParagraphCopier.java:53)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copy(ParagraphCopier.java:42)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphAdder.add(ParagraphAdder.java:45)
	at kr.dogfoot.hwplib.src.MergeTest.main(MergeTest.java:38)

error가 발생하는 곳을 확인해보니 
docInfoAdder.getSourceHWPFile().getDocInfo().getBulletList()의 0번 인덱스에
bulletChar="-" 가 들어있었는데, 파라미터로 들어오는 sourceId가 1로 되어있어 발생한 문제 같습니다....

테스트에 사용한 코드입니다.
```
if (sourceHWPFile != null && targetHWPFile != null) {
            ArrayList<Section> sectionList = targetHWPFile.getBodyText().getSectionList();

            ParagraphListInterface targetFirstSection = sectionList.get(0);
            Section targetSection = sourceHWPFile.getBodyText().getSectionList().get(0);
            for (int i = 0; i < targetSection.getParagraphCount(); i++) {
                Paragraph sourceParagraph = targetSection.getParagraph(i);
                ParagraphAdder paraAdder = new ParagraphAdder(targetHWPFile, targetFirstSection);

                if (i == 0) {
                    String firstLine = sourceParagraph.getNormalString();
                    sourceParagraph.deleteText();
                    sourceParagraph.createText();
                    String newFirstLine = "1. " + firstLine;
                    sourceParagraph.getText().addString(newFirstLine);

                    Paragraph targetLastParagraph = targetFirstSection.getParagraph(targetFirstSection.getParagraphCount() - 1);
                    paraAdder.merge(targetLastParagraph, sourceHWPFile, sourceParagraph);
                } else {
                    paraAdder.add(sourceHWPFile, sourceParagraph);
                }
            }
            HWPWriter.toFile(targetHWPFile, "new" + sourceFileName);
        }
```

**Comment by neolord0** [comment]
bullet 복사 부분에서 인덱스 처리를 잘 못 한 거 같습니다.
수정하였습니다.

**Comment by seopchan** [comment]
테스트 해보았고 잘 작동합니다.
감사합니다!!
