### ISSUE TITLE
문단 복사 시 NullPointerException 발생

### ISSUE THREAD

**Issue by seopchan** [neolord0/hwplib#126]
[layout.hwp.zip](https://github.com/neolord0/hwplib/files/5923555/layout.hwp.zip)
[srcHWP.zip](https://github.com/neolord0/hwplib/files/5923556/srcHWP.zip)

layout파일에 src파일들을 각각 복사를 하면 아래와 같은 에러가 발생합니다.

>Exception in thread "main" java.lang.NullPointerException
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCommonPartCopier.ctrlHeader(GsoCommonPartCopier.java:36)
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCommonPartCopier.copy(GsoCommonPartCopier.java:25)
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.copy(GsoCopier.java:25)
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.container(GsoCopier.java:315)
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.copy(GsoCopier.java:52)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copyControlList(ParagraphCopier.java:95)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copy(ParagraphCopier.java:47)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphAdder.add(ParagraphAdder.java:45)
	at kr.dogfoot.hwplib.src.MergeTest.main(MergeTest.java:38)

srcHWP파일들의 paragraph의 ControlList의 childControlList의 header가 모두 null이어서 발생을 한 것 같습니다.

테스트에 사용한 코드입니다.
```
if (sourceHWPFile != null && targetHWPFile != null) {
            ArrayList<Section> sectionList = targetHWPFile.getBodyText().getSectionList();

            ParagraphListInterface targetFirstSection = sectionList.get(0);
            Section targetSection = sourceHWPFile.getBodyText().getSectionList().get(0);
            for (int i = 0; i < targetSection.getParagraphCount(); i++) {
                Paragraph sourceParagraph = targetSection.getParagraph(i);
                ParagraphAdder paraAdder = new ParagraphAdder(targetHWPFile, targetFirstSection);

                if (i == 0) {
                    String firstLine = sourceParagraph.getNormalString();
                    sourceParagraph.deleteText();
                    sourceParagraph.createText();
                    String newFirstLine = "1. " + firstLine;
                    sourceParagraph.getText().addString(newFirstLine);

                    Paragraph targetLastParagraph = targetFirstSection.getParagraph(targetFirstSection.getParagraphCount() - 1);
                    paraAdder.merge(targetLastParagraph, sourceHWPFile, sourceParagraph);
                } else {
                    paraAdder.add(sourceHWPFile, sourceParagraph);
                }
            }
            HWPWriter.toFile(targetHWPFile, "new" + sourceFileName);
        }
```

**Comment by neolord0** [comment]
이 부분도 수정하였습니다.

**Comment by neolord0** [comment]
객체 묶음 일때.. 문제가 된 거 같습니다.
수정했습니다.

**Comment by seopchan** [comment]
테스트 해보았고 이상없이 동작합니다!!
감사합니다!!
