### ISSUE TITLE
BorderFillAdder의 IndexOutOfBounds 에러

### ISSUE THREAD

**Issue by Eintior** [neolord0/hwplib#140]
ParagraphAdder.add 사용 중 BorderFillAdder 의 processById에서 -1로, equalById에서Index: 1, Size: 1로 발생했습니다.

equalById는 #124, #125 이슈가 비슷한 증상인 것 같아서 해당 코드 참고하여 수정하였는데

processById는 CharShapeAdder를 참고해서 수정해야 할지 인덱스 처리부분을 수정해야 할 지 모르겠습니다...

```
>> processById 오류
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.BorderFillAdder.processById(BorderFillAdder.java:19)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.CharShapeAdder.addAndCopy(CharShapeAdder.java:147)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.CharShapeAdder.processById(CharShapeAdder.java:32)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.StyleAdder.addAndCopy(StyleAdder.java:70)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.StyleAdder.processById(StyleAdder.java:22)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParaHeaderCopier.copy(ParaHeaderCopier.java:17)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copyHeader(ParagraphCopier.java:53)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copy(ParagraphCopier.java:42)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphAdder.add(ParagraphAdder.java:45)
```

equalById 오류는 로그를 잃어버리고 재현도 안되네요...이런

**Comment by neolord0** [comment]
CharShape.getBorderFillId() 가.. 0일때 문제입니다. 

일반적으로는, BorderFill 아이디는 0이 될 수 없는데.. 
아마도,  CharShape.getBorderFillId() 에서만 0값이 들어가는 것 같습니다.
정확한 이유는 알기 힘드나, 이 기능을 추가하면서 테두리/배경이 설정 안 된 경우를 대비한 기본값이라고 추측됩니다.
그래서, 0값일 때는 0으로 넣어주게 처리 했습니다.


public class CharShapeAdder {
    private int addAndCopy(CharShape source) {    
  // target.setBorderFillId(docInfoAdder.forBorderFill().processById(source.getBorderFillId()));
  
     ... 
       if (source.getBorderFillId() == 0) {
            target.setBorderFillId(0);
        } else {
            target.setBorderFillId(docInfoAdder.forBorderFill().processById(source.getBorderFillId()));
        }

       ... 
    } 

}

**Comment by Eintior** [comment]
넵 감사합니다
