### ISSUE TITLE
파싱 오류

### ISSUE THREAD

**Issue by cool7203** [neolord0/hwplib#188]
링크에 있는 다음 문서를 파싱하지 못하네요. 뭐가 문제일까요?

링크 : https://www.hancom.com/etc/hwpDownload.do?gnb0=269&gnb1=271&gnb0=101&gnb1=140
문서 : 한글문서파일형식3.0_HWPML_revision1.2.hwp

코드 :

```
try (InputStream input = getAssets().open("한글문서파일형식3.0_HWPML_revision1.2.hwp")) {
            HWPFile hwpFile = HWPReader.fromInputStream(input);
            TextExtractOption option = new TextExtractOption();
            option.setMethod(TextExtractMethod.InsertControlTextBetweenParagraphText);
            option.setWithControlChar(false);
            option.setAppendEndingLF(true);

            return TextExtractor.extract(hwpFile, option);
        }
```

결과 :

```
java.io.FileNotFoundException: no such entry: "Section1", had: [Section0]
        at kr.dogfoot.hwplib.org.apache.poi.poifs.filesystem.DirectoryNode.getEntry(DirectoryNode.java:291)
        at kr.dogfoot.hwplib.util.compoundFile.reader.CompoundFileReader.getChildStreamReader(CompoundFileReader.java:120)
        at kr.dogfoot.hwplib.reader.HWPReader.section(HWPReader.java:192)
        at kr.dogfoot.hwplib.reader.HWPReader.bodyText(HWPReader.java:180)
        at kr.dogfoot.hwplib.reader.HWPReader.fromInputStream(HWPReader.java:93)
```

**Comment by cool7203** [comment]
답변 감사합니다.
배포용 문서 외에도 hwp 3.0 이하 문서에서도 비슷한 오류가 발생하더군요.
적절한 오류처리가 되면 좋겠습니다.
