### ISSUE TITLE
1.1.5 버전 CtrlHeaderGso 클래스의 unkown 참조 이슈

### ISSUE THREAD

**Issue by tkddn204** [neolord0/hwplib#252]
안녕하세요. 최근에 hwplib을 알게되어 잘 사용하고 있습니다. 감사합니다.
**1.1.5 버전**을 사용하다가 오류를 하나 발견해서 이슈로 등록하고자 합니다.

해당 코드로 테스트를 진행했습니다:
```
public static IntStream paragraphIndex() {
  return IntStream.range(0, 30);
}

@ParameterizedTest
@MethodSource("paragraphIndex")
void readAndGetDocInfo(int paragraphIndex) throws Exception {
    String filePath = "test.hwp"; // 개인적인 파일

    HWPFile originHwpFile = HWPReader.fromFile(filePath);
    HWPFile newHwpFile = BlankFileMaker.make();

    DocInfoAdder docInfoAdder = new DocInfoAdder(originHwpFile, newHwpFile);

    ParagraphCopier paragraphCopier = new ParagraphCopier(docInfoAdder);
    Section originSection = originHwpFile.getBodyText().getSectionList().get(0);
    Section newSection = newHwpFile.getBodyText().getSectionList().get(0);
    Paragraph newParagraph = newSection.addNewParagraph();
    if (originSection.getParagraphCount() <= paragraphIndex) return;
    paragraphCopier.copy(originSection.getParagraph(paragraphIndex), newParagraph); // 오류 발생 라인

    HWPWriter.toFile(newHwpFile, "test_" + paragraphIndex + ".hwp");
}
```

그랬더니 다음과 같은 에러가 발생했습니다:

```
java.lang.NullPointerException
	at kr.dogfoot.hwplib.object.bodytext.control.ctrlheader.CtrlHeaderGso.copy(CtrlHeaderGso.java:334)
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCommonPartCopier.ctrlHeader(GsoCommonPartCopier.java:30)
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCommonPartCopier.copy(GsoCommonPartCopier.java:18)
	at kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.copy(GsoCopier.java:15)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copyControlList(ParagraphCopier.java:136)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copy(ParagraphCopier.java:50)
```

`CtrlHeaderGso` 객체를 사용하는 모든 컨트롤 객체에서 오류가 발생했습니다.

오류 추적을 해보니, 2024버전에 새로 정의한 `unknown` 바이트를 참조하지 못하여 null을 발생시키는 것 같습니다.

1.1.4로 다운그레이드를 했을 때는 해당 오류는 발생하지 않았습니다.

**Comment by neolord0** [comment]
안녕하세요.
에러 수정했고.. 메이븐에 1.1.6 버전으로 올렸습니다.
에러 보고해 주셔서 감사합니다.
