### ISSUE TITLE
한가지 다시 물어보고자 하는 내용이 있어 질문합니다~

### ISSUE THREAD

**Issue by kamsi76** [neolord0/hwplib#52]
테이블 CELL의 여백을 주고자 하는데..
여백은 주어지나 [안 여백 지정] 이라는 내용을 체크해야 적용이 됩니다.
그런데 API를 찾아봐도 그걸 체크할 수 있는 방법이 없네요..ㅜㅜ

![image](https://user-images.githubusercontent.com/25272/58684784-69916900-83b4-11e9-9561-585ed2b48a2a.png)

저부분을 어떻게 해야 체크 되는지 알수 있을까요??

두번째로....

ArrayList<String> result = FieldFinder.getAllClickHereText(hwpFile, "사업장명", TextExtractMethod.OnlyMainParagraph);
for (String string : result) {
	System.out.println(string);
}

전체 누름틀 정보를 가져오는 항목입니다.
문제는 꼬릿말이 없으면 정상적으로 가져오는데
꼬릿말을 넣으면 아래와 같은 오류가 발생합니다.

Exception in thread "main" java.lang.ClassCastException: kr.dogfoot.hwplib.object.bodytext.control.ControlFooter cannot be cast to kr.dogfoot.hwplib.object.bodytext.control.ControlFootnote
at kr.dogfoot.hwplib.tool.objectfinder.forField.gettext.ForControlWithAllField.getFieldText(ForControlWithAllField.java:54)
	at kr.dogfoot.hwplib.tool.objectfinder.forField.ForParagraphList.getAllFieldTextForControl(ForParagraphList.java:194)
	at kr.dogfoot.hwplib.tool.objectfinder.forField.ForParagraphList.getAllFieldText(ForParagraphList.java:128)
	at kr.dogfoot.hwplib.tool.objectfinder.FieldFinder.getAllClickHereText(FieldFinder.java:52)

꼬릿말 부분을 찾으며 형변환을 정상적으로 하지 못하는 듯합니다.
어찌하면 좋을 까요..ㅜㅜ

항상 감사합니다~

**Comment by neolord0** [comment]
회사 일  때문에... 답변이 늦었네요.. 

1)  [안 여백 지정] 속성에 대한 함수는 추가되었습니다. 
Cell.getListHeader().getProperty().isApplyInnerMagin() / setApplyInnerMagin()  함수를 사용하세요.

2) ForControlWithAllField.getFieldText() 에러나는 문제는
 switch()문에서 break; 가 빠져서 그런 거 같습니다.. 수정하였으니 테스트 해보세요..

**Comment by kamsi76** [comment]
감사합니다~~
