### ISSUE TITLE
구버전 한글 파일 파싱 실패 문의

### ISSUE THREAD

**Issue by Chaedae** [neolord0/hwplib#86]
안녕하세요.
좋은 라이브러리 공유해주셔서 너무 감사드립니다.

다름이 아니라 구버전 한글 파일 파싱 시 아래와 같이 오류가 발생하여 문의 드립니다

org.apache.poi.poifs.filesystem.NotOLE2FileException: Invalid header signature; read 0x75636F4420505748, expected 0xE11AB1A1E011CFD0 - Your file appears not to be a valid OLE2 document
	at org.apache.poi.poifs.storage.HeaderBlock.<init>(HeaderBlock.java:144)
	at org.apache.poi.poifs.storage.HeaderBlock.<init>(HeaderBlock.java:113)
	at org.apache.poi.poifs.filesystem.NPOIFSFileSystem.<init>(NPOIFSFileSystem.java:301)
	at org.apache.poi.poifs.filesystem.POIFSFileSystem.<init>(POIFSFileSystem.java:81)
	at kr.dogfoot.hwplib.util.compoundFile.reader.CompoundFileReader.<init>(CompoundFileReader.java:48)
	at kr.dogfoot.hwplib.reader.HWPReader.fromInputStream(HWPReader.java:56)
	at kr.dogfoot.hwplib.reader.HWPReader.fromFile(HWPReader.java:32)
	at test.Test.main(Test.java:41)

대상 파일 첨부드립니다

[2001.zip](https://github.com/neolord0/hwplib/files/4126365/2001.zip)

아주 오래전 버전의 한글 파일들에 대해서 해당 오류가 발생하는것 같습니다..
(97 등..)
확인 한번 부탁 드리겠습니다..

**Comment by neolord0** [comment]
한글 97포맷(3.0)은 이 라이브러리에서 읽을 수 있는 한글 파일(5.0)과는 완벽히 다른 포맷입니다.
이 라이브러리는 한글 97포맷을 지원하지 않습니다. --; 

전에 회사 업무로 다뤄봐서.. 대략적으로는 알곤 있는데요.. 
아마도, 별도로 라이브러리를 만들어야 할 거 같네요.

아니면, 한글에서 파일을 2000대 버전으로 업글(읽었다 다시 저장)에서 사용하시길 권장드립니다.

**Comment by Chaedae** [comment]
> 한글 97포맷(3.0)은 이 라이브러리에서 읽을 수 있는 한글 파일(5.0)과는 완벽히 다른 포맷입니다.
> 이 라이브러리는 한글 97포맷을 지원하지 않습니다. --;
> 
> 전에 회사 업무로 다뤄봐서.. 대략적으로는 알곤 있는데요..
> 아마도, 별도로 라이브러리를 만들어야 할 거 같네요.
> 
> 아니면, 한글에서 파일을 2000대 버전으로 업글(읽었다 다시 저장)에서 사용하시길 권장드립니다.
